## action.yml
name: 'Google Bigquery "Deploy table, view and other structure definitions" Action for Github Action'
description: 'Creates a Bigquery structure if it does not exists, else updates it'
author: 'Jash Parekh <me@jashparekh.com>'
branding:
  icon: 'activity'
  color: 'orange'
inputs:
  gcp_project:
    description: 'The name of the GCP project you want to deploy'
    required: true
  gcp_region:
    description: 'GCP region where the cloud function is hosted'
    required: true
  cloud_function_name:
    description: 'Name of the cloud function in GCP'
    required: true
  cloud_function_directory:
    description: 'The directory in your repository where are you storing the code files for cloud function'
    required: true
  credentials:
    description: 'Service account to autheticate with BigQuery'
    required: true
  debug_mode:
    description: 'Enable debug mode'
    required: false
runs:
  using: 'docker'
  image: 'Dockerfile'
