name: "Integration Test"
on:
  pull_request: {}
  push:
      branches: ["main"]

env:
  PYTHON_VERSION: "3.10.1"

jobs:
  deploy_schemas:
    runs-on: ubuntu-latest
    name: Deploy cloud functions
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v2
      - name: Deploy schemas to BigQuery
        uses: ./ # Uses an action in the root directory
        env:
          gcp_project: "wf-gcp-us-ae-buyfair-dev"
          gcp_region: "us-central1"
          cloud_function_name: "test_cloud_function"
          cloud_function_directory: "functions/test_cloud_function"
          credentials: ${{ secrets.GCP_SERVICE_ACCOUNT }}
